root: true
env:
  es2022: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'import'
  - 'prettier'
ignorePatterns:
  - '**/dist/**'
  - '**/node_modules/*'
rules:
  prettier/prettier: error
  import/order:
    - error
    - newlines-between: always
overrides:
  - files:
      - 'src/**/*.ts?(x)'
    parserOptions:
      project: './tsconfig.json'
    rules:
      '@typescript-eslint/no-floating-promises': 'error'
      '@typescript-eslint/no-explicit-any': 'warn'
      '@typescript-eslint/no-unused-vars': 'warn'